services:
  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    restart: unless-stopped
    ports:
      - "19999:19999"
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true
