apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vps-system

resources:
  - ../base/namespace.yaml
  - ../base/configmap.yaml
  - ../base/secret.yaml
  - ../base/storageclass.yaml
  - ../base/pvc.yaml

commonLabels:
  app.kubernetes.io/part-of: vps-starter-kit
  app.kubernetes.io/managed-by: kustomize

generatorOptions:
  disableNameSuffixHash: true
