services:
  redis:
    image: ${REDIS_IMAGE}
    container_name: ${REDIS_CONTAINER_NAME}
    restart: unless-stopped
    env_file:
      - .env
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./backups:/backups
    expose:
      - "6379"
    networks:
      - db_network

volumes:
  redis_data:

networks:
  db_network:
    external: true
